### ISSUE TITLE
support for emmet

### ISSUE THREAD

**Issue by GingerBear** [GingerBear/vscode-liquid#1]

**Comment by GingerBear** [comment]
turns out vscode doesn't support emmet on language that is out side of a hardcoded list, should be able to have a update soon https://github.com/Microsoft/vscode/issues/9500

**Comment by GingerBear** [comment]
seems to be resolved

**Comment by jcat4** [comment]
In case anyone comes across this and doesn't know what to do like me, I just figured it out.

In your User Settings JSON file (Settings -> User Settings -> ... -> Open settings.json),
add the following:

`"emmet.includeLanguages": {
        "liquid": "html"
    }`

Then emmet should start working as normal in your liquid files for HTML autocompletions.
