### ISSUE TITLE
[0.1.0] Syntax and highlighting bug

### ISSUE THREAD

**Issue by jonathanmoore** [GingerBear/vscode-liquid#16]
With the release of 0.1.0, syntax highlighting is broken with basic HTML inside liquid files.  I'm not fully up to speed on VS extensions, but the following lines are the cause.  Testing locally and removing those lines fixes the issue and everything highlights as expected.
https://github.com/GingerBear/vscode-liquid/blob/master/syntaxes/liquid.tmLanguage#L63-L70

My assumption is that the CSS and JS syntax and reserved words are kicking in throughout the entire file with certain characters and throwing off the rest of the highlighting.

![image](http://cloud.jonathanmoore.com/7ade83e17187/Screen%252520Recording%2525202018-12-12%252520at%25252006.17%252520PM.gif)

### 0.0.3 Highlighting
![image](https://user-images.githubusercontent.com/454095/49911916-09762d00-fe3d-11e8-9199-30aef0b86611.png)

### 0.1.0 Highlighting
![image](https://user-images.githubusercontent.com/454095/49911931-1f83ed80-fe3d-11e8-9322-24a25c87c1db.png)

Related issue: #11

**Comment by GingerBear** [comment]
thanks for the feedback, I just reverted the commit that cause this issue and published a new version.
