### ISSUE TITLE
Does not properly set file type when viewing .scss.liquid files

### ISSUE THREAD

**Issue by bananabread** [GingerBear/vscode-liquid#3]
When working with .scss.liquid files it the type is set to HTML Liquid, so the syntax highlighting is incorrect.

**Comment by GingerBear** [comment]
seems to be a limitation on the extension to for .liquid to display scss, I will take a further look. 

At the mean time, I think you can manually set syntax to scss by click "HTML Liquid" at the right bottom corner of vscode, and choose sass

**Comment by ADTC** [comment]
You can add special exceptions to your User Settings:
```
    "files.associations": {
        "*.scss.liquid": "scss",
        "*.js.liquid": "javascript"
    }
```
But this means those files get formatted with SCSS or JavaScript but not Liquid anymore. It would have been nice to superimpose Liquid on SCSS (for example).
