### ISSUE TITLE
Error: The mode has failed while tokenizing the input.

### ISSUE THREAD

**Issue by spencerthayer** [GingerBear/vscode-liquid#5]
The new update is broken. I'm receiving the following error, `Error: The mode has failed while tokenizing the input.` every time I open a liquid file now and syntax coloring/highlighting are not working. Everytime I use the keyboard that error pops up again. When I uninstall the extension the error goes away. Sadly there is no liquid language support anymore.

I really need this to work today. Any tips on how to roll back the update?

I found this page from here, https://marketplace.visualstudio.com/items?itemName=neilding.language-liquid

**Comment by GingerBear** [comment]
@spencerthayer
Last update of the extension is 1 years ago. So it's most likely it's the update in vscode that breaks the extension. 

I will try to take a look later today if it can be fixed.

**Comment by GingerBear** [comment]
hey @spencerthayer , I just try on latest vscode (1.12.1) on mac, all seems to be fine. Maybe you can re-install vscode to see if it fixes
