### ISSUE TITLE
Autocomplete for HTML

### ISSUE THREAD

**Issue by iansoper** [GingerBear/vscode-liquid#7]
I'm not able to use HTML autocomplete when I have the file set to HTML Liquid. For an example if I want to create an `<section>` tag, typing in `sec` doesn't bring up any options for the section html tag. Is there a way to configure this?

**Comment by summer18** [comment]
Would like to know this as well

**Comment by GingerBear** [comment]
@iansoper @summer18 
HTML autocomplete in vscode is provided by emmet, you can achieve that in liquid by adding your vscode config 
```
  "emmet.includeLanguages": {
    "liquid": "html"
  }
```

here is more info about the config https://code.visualstudio.com/docs/languages/html#_emmet-snippets
